//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yammer.Chat.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yammer.Chat.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coworkers.
        /// </summary>
        public static string AddCoworkersButtonText {
            get {
                return ResourceManager.GetString("AddCoworkersButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Coworkers.
        /// </summary>
        public static string AddCoworkersPageHeaderText {
            get {
                return ResourceManager.GetString("AddCoworkersPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yammer Chat.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the application&apos;s live tile with the number of new chat messages..
        /// </summary>
        public static string BackgroundAgentDescriptionText {
            get {
                return ResourceManager.GetString("BackgroundAgentDescriptionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversation Details.
        /// </summary>
        public static string ConversationDetailsHeaderText {
            get {
                return ResourceManager.GetString("ConversationDetailsHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again!.
        /// </summary>
        public static string DefaultErrorText {
            get {
                return ResourceManager.GetString("DefaultErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string EditMugshotText {
            get {
                return ResourceManager.GetString("EditMugshotText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string InvalidCredentialsText {
            get {
                return ResourceManager.GetString("InvalidCredentialsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, that&apos;s not a valid email..
        /// </summary>
        public static string InvalidEmailText {
            get {
                return ResourceManager.GetString("InvalidEmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap to like this message.
        /// </summary>
        public static string LikeButtonText {
            get {
                return ResourceManager.GetString("LikeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Likes.
        /// </summary>
        public static string LikersPluralText {
            get {
                return ResourceManager.GetString("LikersPluralText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 Like.
        /// </summary>
        public static string LikersSingularText {
            get {
                return ResourceManager.GetString("LikersSingularText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding coworkers to conversation....
        /// </summary>
        public static string LoadingAddingParticipantsToThread {
            get {
                return ResourceManager.GetString("LoadingAddingParticipantsToThread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logging in....
        /// </summary>
        public static string LoadingLogInText {
            get {
                return ResourceManager.GetString("LoadingLogInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving new picture....
        /// </summary>
        public static string LoadingMugshotUploadText {
            get {
                return ResourceManager.GetString("LoadingMugshotUploadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending picture....
        /// </summary>
        public static string LoadingSendImageText {
            get {
                return ResourceManager.GetString("LoadingSendImageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending message....
        /// </summary>
        public static string LoadingSendMessageText {
            get {
                return ResourceManager.GetString("LoadingSendMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string LoadingText {
            get {
                return ResourceManager.GetString("LoadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading messages....
        /// </summary>
        public static string LoadingThreadsText {
            get {
                return ResourceManager.GetString("LoadingThreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading messages....
        /// </summary>
        public static string LoadMessagesText {
            get {
                return ResourceManager.GetString("LoadMessagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work email.
        /// </summary>
        public static string LoginEmailWatermark {
            get {
                return ResourceManager.GetString("LoginEmailWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LoginPasswordWatermark {
            get {
                return ResourceManager.GetString("LoginPasswordWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogoutText {
            get {
                return ResourceManager.GetString("LogoutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to liked by.
        /// </summary>
        public static string MessageLikedByText {
            get {
                return ResourceManager.GetString("MessageLikedByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sent from.
        /// </summary>
        public static string MessageSentFromText {
            get {
                return ResourceManager.GetString("MessageSentFromText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Conversation.
        /// </summary>
        public static string NewConversationPageHeaderText {
            get {
                return ResourceManager.GetString("NewConversationPageHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string NewThreadAppBarButtonText {
            get {
                return ResourceManager.GetString("NewThreadAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with someone.
        /// </summary>
        public static string NewThreadHintText {
            get {
                return ResourceManager.GetString("NewThreadHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no one liked this yet.
        /// </summary>
        public static string NoOneLikedMessageYetText {
            get {
                return ResourceManager.GetString("NoOneLikedMessageYetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It looks like you haven&apos;t chatted with anyone yet..
        /// </summary>
        public static string NoThreadsText {
            get {
                return ResourceManager.GetString("NoThreadsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login was denied..
        /// </summary>
        public static string OAuthDeniedErrorText {
            get {
                return ResourceManager.GetString("OAuthDeniedErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We require your permission on Yammer.com to login. Use the button below to start..
        /// </summary>
        public static string OAuthExplanationText {
            get {
                return ResourceManager.GetString("OAuthExplanationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured. Please contact yammernow@outlook.com for support..
        /// </summary>
        public static string OAuthGenericErrorText {
            get {
                return ResourceManager.GetString("OAuthGenericErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login via Yammer.com.
        /// </summary>
        public static string OAuthLoginButtonText {
            get {
                return ResourceManager.GetString("OAuthLoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Participants.
        /// </summary>
        public static string ParticipantsCountText {
            get {
                return ResourceManager.GetString("ParticipantsCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who would you like to message?.
        /// </summary>
        public static string ParticipantSearchText {
            get {
                return ResourceManager.GetString("ParticipantSearchText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string ProfileAboutMeText {
            get {
                return ResourceManager.GetString("ProfileAboutMeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell your coworkers about yourself..
        /// </summary>
        public static string ProfileAboutMeWatermarkText {
            get {
                return ResourceManager.GetString("ProfileAboutMeWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string ProfileEditFirstNameText {
            get {
                return ResourceManager.GetString("ProfileEditFirstNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your job title.
        /// </summary>
        public static string ProfileEditJobTitleText {
            get {
                return ResourceManager.GetString("ProfileEditJobTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string ProfileEditLastNameText {
            get {
                return ResourceManager.GetString("ProfileEditLastNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your mobile phone number.
        /// </summary>
        public static string ProfileEditMobilePhoneText {
            get {
                return ResourceManager.GetString("ProfileEditMobilePhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add your work phone number.
        /// </summary>
        public static string ProfileEditWorkPhoneText {
            get {
                return ResourceManager.GetString("ProfileEditWorkPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string ProfileMobilePhoneText {
            get {
                return ResourceManager.GetString("ProfileMobilePhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string ProfilePageTitleText {
            get {
                return ResourceManager.GetString("ProfilePageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No number provided..
        /// </summary>
        public static string ProfilePhoneWatermarkText {
            get {
                return ResourceManager.GetString("ProfilePhoneWatermarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving updates....
        /// </summary>
        public static string ProfileSavingText {
            get {
                return ResourceManager.GetString("ProfileSavingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work.
        /// </summary>
        public static string ProfileWorkPhoneText {
            get {
                return ResourceManager.GetString("ProfileWorkPhoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yammer Chat feedback.
        /// </summary>
        public static string SendFeedbackSubjectText {
            get {
                return ResourceManager.GetString("SendFeedbackSubjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send.
        /// </summary>
        public static string SendReplyAppBarButtonText {
            get {
                return ResourceManager.GetString("SendReplyAppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string SentFromMobileText {
            get {
                return ResourceManager.GetString("SentFromMobileText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string SentFromWebText {
            get {
                return ResourceManager.GetString("SentFromWebText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application version.
        /// </summary>
        public static string SettingsApplicationVersionText {
            get {
                return ResourceManager.GetString("SettingsApplicationVersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat connection status.
        /// </summary>
        public static string SettingsChatConnectionStatusText {
            get {
                return ResourceManager.GetString("SettingsChatConnectionStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Feedback.
        /// </summary>
        public static string SettingsSendFeedbackButtonText {
            get {
                return ResourceManager.GetString("SettingsSendFeedbackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsText {
            get {
                return ResourceManager.GetString("SettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Log In.
        /// </summary>
        public static string SsoLoginPageTitleText {
            get {
                return ResourceManager.GetString("SsoLoginPageTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string StringConcatenatorText {
            get {
                return ResourceManager.GetString("StringConcatenatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message....
        /// </summary>
        public static string ThreadReplyHintText {
            get {
                return ResourceManager.GetString("ThreadReplyHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve liked this message.
        /// </summary>
        public static string UnlikeButtonText {
            get {
                return ResourceManager.GetString("UnlikeButtonText", resourceCulture);
            }
        }
    }
}
